# Generated by Django 3.1.1 on 2020-09-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='question1',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question10',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question11',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question12',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question13',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question14',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question15',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question16',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question17',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question18',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question19',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question2',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question20',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question3',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question4',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question5',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question6',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question7',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question8',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='question9',
            field=models.CharField(default='0000000', max_length=50),
            preserve_default=False,
        ),
    ]
