# Generated by Django 3.1.1 on 2020-09-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_auto_20200911_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='question1',
            field=models.CharField(choices=[('option1', 'red'), ('option2', 'blue'), ('option3', 'black'), ('option4', 'white')], max_length=50),
        ),
    ]
