# Generated by Django 3.1.1 on 2020-09-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_auto_20200911_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='credentials2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.IntegerField(default=True, null=True)),
                ('question1', models.CharField(blank=True, max_length=50, null=True)),
                ('question2', models.CharField(blank=True, max_length=50, null=True)),
                ('question3', models.CharField(blank=True, max_length=50, null=True)),
                ('question4', models.CharField(blank=True, max_length=50, null=True)),
                ('question5', models.CharField(blank=True, max_length=50, null=True)),
                ('question6', models.CharField(blank=True, max_length=50, null=True)),
                ('question7', models.CharField(blank=True, max_length=50, null=True)),
                ('question8', models.CharField(blank=True, max_length=50, null=True)),
                ('question9', models.CharField(blank=True, max_length=50, null=True)),
                ('question10', models.CharField(blank=True, max_length=50, null=True)),
                ('question11', models.CharField(blank=True, max_length=50, null=True)),
                ('question12', models.CharField(blank=True, max_length=50, null=True)),
                ('question13', models.CharField(blank=True, max_length=50, null=True)),
                ('question14', models.CharField(blank=True, max_length=50, null=True)),
                ('question15', models.CharField(blank=True, max_length=50, null=True)),
                ('question16', models.CharField(blank=True, max_length=50, null=True)),
                ('question17', models.CharField(blank=True, max_length=50, null=True)),
                ('question18', models.CharField(blank=True, max_length=50, null=True)),
                ('question19', models.CharField(blank=True, max_length=50, null=True)),
                ('question20', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='credentials',
        ),
    ]
