# Generated by Django 3.1.1 on 2020-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_auto_20200911_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='credentials3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.IntegerField(default=True, null=True)),
                ('favcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('sociallife', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('sexuality', models.CharField(blank=True, max_length=50, null=True)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('rstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('dept', models.CharField(blank=True, max_length=50, null=True)),
                ('favmeal', models.CharField(blank=True, max_length=50, null=True)),
                ('siblings', models.CharField(blank=True, max_length=50, null=True)),
                ('tvshow', models.CharField(blank=True, max_length=50, null=True)),
                ('hometown', models.CharField(blank=True, max_length=50, null=True)),
                ('priedu', models.CharField(blank=True, max_length=50, null=True)),
                ('secedu', models.CharField(blank=True, max_length=50, null=True)),
                ('sports', models.CharField(blank=True, max_length=50, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('anime', models.CharField(blank=True, max_length=50, null=True)),
                ('favanime', models.CharField(blank=True, max_length=50, null=True)),
                ('personality', models.CharField(blank=True, max_length=50, null=True)),
                ('otherpersonality', models.CharField(blank=True, max_length=50, null=True)),
                ('clientname', models.CharField(default=True, max_length=50, null=True)),
                ('imagetogether', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='credentials2',
        ),
    ]
